# Generated by Django 4.0.2 on 2022-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_testmodel_registry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='registry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
